### ISSUE TITLE
java.lang.ClassCastException: com.ibm.notes.smartfile.RunOnReplication incompatible with org.eclipse.core.runtime.jobs.Job

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/AFSfNC#1]
I've installed AFSfNC from the update site. When I launch Notes (9.0.1 FP2 Windows) it hangs when trying to replicate "IBM SmartFile Action". It gives the error in the trace:
CLFMW0065E: Error in processing core's synchronously sent IPC request
java.lang.ClassCastException: com.ibm.notes.smartfile.RunOnReplication incompatible with org.eclipse.core.runtime.jobs.Job
    at com.ibm.workplace.notes.sync.SyncHandler.handleStart(Unknown Source)
    at com.ibm.workplace.notes.sync.SyncHandler.handleEvent(Unknown Source)
    at com.ibm.workplace.notes.ipc.internal.DispatcherRegistry$IpcDescriptor.handleEvent(Unknown Source)
    at com.ibm.workplace.noteswc.ipc.NotesDispatcherService.sendEvent(Unknown Source)
    at com.ibm.workplace.noteswc.NotesListener$23.run(Unknown Source)
    at org.eclipse.core.internal.jobs.Worker.run(Unknown Source)

I tried launching by using the command line setting:
rcplauncher.exe -console -config notes -vmargs -Duser.language=en -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8020
and adding these lines to the rcpinstall.properties:
com.ibm.rcp.provisioning.level=FINEST
com.ibm.rcp.toolbox.level=FINEST 
As Notes launches, I can see messages saying it's installing the plugin fine.

If I issue the osgi command "ss com.ibm.notes.smartfile", it's showing as ACTIVE and also there are no unresolved constraints if I issue "diag com.ibm.notes.smartfile.notes" (which I would not expect because it's showing as ACTIVE.

If I go to the Preferences, there is an entry in the navigation for SmartFile, but it just has the buttons Restore Defaults and Apply. From looking at the code, I would expect it to have fields for the mail file etc.

I'm not sure how to debug from Notes, but I got errors building the com.ibm.notes.smartfile project in Eclipse after amending the JRE System Library to my Notes JRE.

**Comment by Stwissel** [comment]
The client API seems to have changed in visibility. I'll have a look once time permits
